name: '🐞 Bug Report'
description: 'Report an issue to help the project improve.'
title: '[Bug] '
labels: ['type: bug']

assignees:
  - lotyp

body:
  - type: markdown
    attributes:
      value: '🐞 Bug Report'

  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'Type here...'
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: 'Is this a regression?'
      description: |
        'Did this behaviour use to work in the previous version?
        Yes, the last version in which this bug was not present was: ...'
      placeholder: 'Yes or No and details...'
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'To Reproduce'
      description: |
        'Steps to reproduce the error:
        1. Use x argument / navigate to...
        2. Fill this information...
        3. Go to...
        4. See error'
      placeholder: 'Describe the steps...'
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: 'Expected behaviour'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'Type here...'
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: 'Media prove'
      description: 'If applicable, add screenshots or videos to help explain your problem.'
      placeholder: 'Upload files or leave a link here...'
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 'Your environment'
      description: |
        'Please provide information about your environment.
        * OS: [e.g. Ubuntu]
        * PHP version: [e.g. 8.2.2]
        * Package version: [e.g. 1.0.0]
      placeholder: 'Fill out all applicable fields...'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: 'Add any other context or additional information about the problem here.'
      placeholder: 'Type here...'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        📛 To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md` and the Contribution Guidelines at `.github/CONTRIBUTING.md` 📛
